- spacemacs-common.el
When you have a split the - active - mode-line "height looks shorter because there's no border.
I Understand that it looks nicer without border and the inactive needs contrast, but, I added neutral color so it looks as nice as possible.
> polish - mode-line same height active / inactive

- spacemacs-common.el
That face got removed in https://github.com/emacs-helm/helm/commit/326c939b09a23f0541ae37c79aeb266d46562da4
> Remove obsolete helm-grep-running face

- spacemacs-common.el
With regard to the `spacemacs-theme-org-height' user option.
> Conditionally enlarge font in org-scheduled-today

- spacemacs-common.el
String delimiters and operators are hardly visible in enh-ruby-mode.
Setting them as seen in python mode (as that's what I use and looked for comparison) for making them visible.
> string delem, operators visible in enh-ruby-mode

- spacemacs-common.el
I'm not sure what the procedure is for adding new mode-specific bits of theming, so if there's another place I should submit this request then just let me know.
At some stage I guess someone should do a proper "subtheme" for `mu4e`, but for the moment this replaces the a garish bright green (since `mu4e-header-key-face` inherits from `message-header-name`) and seems more pleasing (to me, at least).
> add color defn for mu4e-header-key-face

- spacemacs-common.el
Another PR to add colors for a mode - in this case `Man-mode`.
Mostly, this is motivated by the fact that I switched to spacemacs-theme from monokai, and there are a few mode-specific colours that I miss. I admit that I'm not a colours-knowing-expert guy, so I'm totally fine if you want to tweak the colors that I've chosen - the main thing I like is that there are *some* pretty colors.
In future, do you want extra mode-specific colors done this way? I'm aware that not everyone likes it to look the way I do. I'd be happy to just set up these colors in my init file, except the way that the theme (and emacs themes in general, it seems) do the name -> colour mapping is a bunch of `let` bindings in a bigol' macro, so it's tricky to use those mappings elsewhere in one's init file. Still, I'm …
> add colours for man pages

- spacemacs-common.el
Add theme support for `popup` and `auto-complete`. `auto-complete` uses `popup`, so add support for them together.
> Support popup and auto-complete

- spacemacs-common.el
Add support for [highlight-symbol.el](https://github.com/nschum/highlight-symbol.el) to highlight occurrences of the symbol at point throughout the current buffer.
Went with `bg2`
`act2` also looks good..
> Support highlight-symbol.el

- spacemacs-common.el
This was sort of talked about in gitter. This is what I came up with to make it a little less bright. It moves the bg color to the fg and uses the -bg variants for the background.
> Change diff-hl faces to be less bright

- spacemacs-common.el
bg1 matches the background of the code... so when the fringe shows up (as with diff-hl) it looks like there are spaces at the start of the line, which can be confusing. This changes the fringe background to match the linum background as they're essentially a part of the same thing (at least in my mind).
> Change fringe background to match linum-mode

- spacemacs-common.el
please review tabbar changes. a tabbar is at the top of the screen showing the currently opened buffers.
#66
> add tabbar faces

- README.md
- spacemacs-common.el
This also adds a `highlight-dim` color for, well, dimmer highlights. Here I use
it for highlighting unread email.
> Theme notmuch.

- spacemacs-common.el
This patch themes `elfeed-search-date-face`, employing one of the provided header colours. I've chosen `head2` over `head1` because of the latter's similarity to the face used for the feed itself.
At present, the theme does not provide any styling for this face. This is how it currently looks:
And with the new `head2` colour:
> Add additional support for elfeed's date face

- spacemacs-common.el
Thanks for themeing mu4e! 
This is a small fix. mu4e-maildirs is an extension that shows the maildirs separately in mu4e. Right now they show up as a weird pinkish color, this makes it so that they get the "head2" color.
> Make mu4e-maildirs headers head2

- README.md
- spacemacs-common.el
This PR adds an option to enable italics for comments.
- By default the new option is disabled (for backwards compatibility)
- Recommendation is once new option is enabled, comment bg option should be disabled (for better contrast)
- Add a new `comment-light` color, for better looking comments once italics are turned on
◉ `spacemacs-theme-comment-bg`
◯ `spacemacs-theme-comment-italic`
◉ `spacemacs-theme-comment-bg`
◉ `spacemacs-theme-comment-italic`
◯ `spacemacs-theme-comment-bg`
◉ `spacemacs-theme-comment-italic`
> Add custom option to enable italics for comments

- spacemacs-common.el
Org 9.1 makes 'auto the default value for org-agenda-align-tags-to-column, which
pushes tags to the right of the agenda window. If we change the height of agenda
items, though, this pushes them too far, resulting in ugly line wrapping.
> Fix org-agenda tag alignment

- spacemacs-common.el
When using whitespace mode I turn both, spaces and tabs to see what is used where and how. This way tabs don't obscure the view as they do with the default foreground. Make them look the same the spaces do now.
> Use the same face for whitespace tabs as for spaces

- spacemacs-common.el
- show-paren-match and sp-show-pair-match-face should have identical
values since they do the same thing
- Remove underlining from parens because it looks odd
- Theme show-paren-match-expresssion
- Theme show-paren-mismatch to better resemble
show-paren-match/sp-show-pair-match-face
> Improve parens

- spacemacs-common.el
Currently in an active buffer, it's pink/purple on top of a slightly
different pink/purple, which isn't great looking. This changes it to
yellow, which looks better.
> Change mu4e-modeline-face from func to yellow

- spacemacs-common.el
The `pdf-tools` package has a `pdf-view-midnight-minor-mode` with bright text on dark background. Using `spacemacs-light/dark` colors makes it look nicer.
> add support for pdf-view-midnight-minor-mode

- spacemacs-common.el
Spacemacs theme makes headings of org items level 1 and 2 inherit bold weight without apparent way to customise it.
The same goes for agenda (priority) items, which are bold.
This commit adds two custom variables:
- spacemacs-theme-org-bold
controls if level 1 and 2 items should be bold or not
default: t
- spacemacs-theme-org-priority-bold
controls if items in the agenda should be bold
default: t
> Added support to customise bold headings of org levels and priority

- spacemacs-common.el
Hi! Did I mentioned earlier that spacemacs-theme rulezzz? :D
Anyways, I've added a handler for web-mode's current element highlighting. Tried couple existing (and new) colors and decided to try `bg3`. Couple screenshots:
What do you think? Hope it'll be useful!
Much love
> Add web-mode-current-element-highlight-face

- spacemacs-common.el
Simply inherits from the org-mode header faces
> Add support for outline-minor-mode

- spacemacs-common.el
Problem: the `keyword` colors are used for the `diff{, -indicator, -refine}-changed` faces, if the `keyword` color is changed in the future, then it probably shouldn't effect the diff face colors.
Solution: use `blue` to match the `ediff-current-diff-C` face, and currently the `blue` and `keyword` colors are identical.
> Uncouple keyword color from diff changed faces

- spacemacs-common.el
Problem: The `ediff-current-diff-{A, B}` faces use the `red-bg-s` and `green-bg-s` colors, but the `ediff-current-diff-C` face use the non `-s`, `blue-bg` colors.
Solution: use the `blue-bg-s` color for the `ediff-current-diff-C` face.
---
> Unify ediff-current-diff-{A,B,C} background colors

- spacemacs-common.el
This also makes the light themes diff refined text much more readable.
There's no major difference between the dark themes before and after screenshots, so I only included the light theme.
> Change diff refine fg to match ediff fine diff fg

- spacemacs-common.el
box borders for unread items seems to cause performance issues with
the light theme.
This is also a strange default anyways...
Signed-off-by: William Casarin <jb55@jb55.com>
> notmuch: fix performance issues with light theme

- spacemacs-common.el
Just noticed that tabbar did't had an unselected modified face so decided to add it so it looks better. Here's how it looks:
> Added selected/unselected modified face for tabbar

- spacemacs-common.el
Fixes issue where the local variable used in the loop for setting custom theme colors conflicted with an existing color variable. This fixes problem discussed in #151
> Make sure custom themes can change all color variables

- spacemacs-common.el
The `term-color-*` faces are weird in that they need both `:foreground` and `:background` set in order to work correctly.
https://raw.githubusercontent.com/fikovnik/bin-scripts/master/color-test.sh does not work correctly on the current version, the background does not change at all. I initially thought it was wrong but this change seems to work, at least for me.
The Nord theme does this as well: https://github.com/arcticicestudio/nord-emacs/blob/2fc8fe41105d995a8c5d2bad0443ad3ae45c2573/nord-theme.el#L278-L285
> Fix term colors

- spacemacs-common.el
This pull request is needed to distinguish the different backgrounds between the posframe and the open buffer **when solaire-mode is enabled**.
Here's a quick before-and-after, using the **scratch** buffer as an example for solaire-mode. Note the **lack** of contrast if ivy-posframe share the same background color as the open buffer.
> Add support for ivy-posframe

- spacemacs-common.el
I'm not sure if this is an intentional decision or potentially a bug. But normally (as found in most other modern editors), users would expect the tooltip common faces of candidates to be highlighted whether being selected or not. I find the behaviour to disable the common highlight when the candidate is selected to be inconsistent, and at times, confusing and less expressive.
Please keep me updated of your decision, looking forward that this'll be fixed :)
> Make company tooltip common faces consistent

- spacemacs-common.el
Added faces for the lsp-mode features I use. This should fix #143 since that face is lsp-ui-sideline-code-action, though I’m not sure comp is the right color. (That face is used for actions you can click to modify the code at point in particular ways. Clangd for C/C++ offers to expand preprocessor macros f.ex.)
> Add some lsp-mode faces

- spacemacs-common.el
It is required per ivy-format-function-line doc string:
```
"... Note that since Emacs 27, ‘ivy-current-match’ needs to have :extend t attribute.
It has it by default, but the current theme also needs to set it."
```
> [emacs27] add :extend for ivy-current-match

- spacemacs-common.el
Without it,  it renders with default dark-orange.
> Add sh-mode faces

- spacemacs-common.el
If using spacemacs-theme with `spacemacs-theme-org-height` set to `t`, then `org-mode` headings of level 1-3 will have non-standard heights so that higher level headlines "stick out" more, which is aesthetically pleasing. However, if one enables `org-columns` (with e.g., `C-c C-x C-c`), then things will be misaligned (see [this issue on `spacemacs` repo](https://github.com/syl20bnr/spacemacs/issues/14058)), since the column headers are (likely) using the standard face height, but any level 1-3 headers that appear in the column view table will have differing heights.
The `org-column` face is overlaid on top of `org-level-{1,2,3}` but any unspecified lower attributes "shine through" and thus different rows of the "table" generated by `org-columns` have different `height` and so things don't …
> Update org-column face to use default height

- spacemacs-common.el
Upstream introduced several new faces as well fixed typo in the name of an existing face name (`ahs-plugin-defalt-face`). This commit fixes these issues by applying unobtrusive background highlighting, the same way it is already implemented for `ahs-face`.
Here are screenshots from my Spacemacs setup. Before:
After:
fixes: #186
> Improve handling of auto-highlight-symbol

- spacemacs-common.el
- spacemacs-theme-pkg.el
Hi!
I am investigating if we could add this package to [NonGNU ELPA](http://elpa.nongnu.org/) (see link), a new Emacs Lisp package archive that will be enabled by default in Emacs 28. This means that users of that version or later will be able to install this package without any configuration: they can just run `M-x list-packages` and install it out of the box. We hope that this will improve Emacs and help bring new users to this package and others.
The main difference between NonGNU ELPA and MELPA is that only stable versions of packages are released. A new release will be made automatically when you bump the "Version" commentary header in this repository, as I do in this commit. In the future, you can bump the package version (thereby releasing a new version) when you think it makes …
> Bump version to 0.2 for NonGNU ELPA

- spacemacs-common.el
Not much of a highlight when it's the same as `solaire-default-face`
> Fix solaire-hl-line-face background

- spacemacs-theme.el
window-tool-bar is a new mode on GNU ELPA and bundled with Emacs 30.
> Add support for window-tool-bar

- spacemacs-theme.el
This PR makes the font weight of `lazy-highlight`consistent with the other faces when default font is set not to `normal`.
before:
after:
> Improve lazy-highlight

- spacemacs-theme.el
Added faces for dired-subtree. I originally struggled with whether or not to use different dark background colors to represent the depths, but then I referred to [comment](https://github.com/protesilaos/modus-themes/blob/613f95341246746c3def202e67b27a315560d6f4/modus-themes.el#L2180-L2183) in modus-theme and found that it worked well, as there're only four different dark background colors provided in spacemacs-theme, but dired-subtree defines six subtree depth faces.
> Add support for dired-subtree

- spacemacs-theme.el
> Add support for helm-rg
